### ISSUE TITLE
bitcoinfees.earn.com API is giving bad data on fees

### ISSUE THREAD

**Issue by bretton** [mcscrad/price-poller#1]
Problem: `.get("https://bitcoinfees.earn.com/api/v1/fees/recommended")` is old data and incorrect fees for current market conditions on 20 April 2021.

Rather use `.get("https://mempool.space/api/v1/fees/recommended")` (from https://mempool.space/api)

**Comment by yawhide** [comment]
hey @bretton great suggestion! let me take a look and i'll respond once I have implemented it.

**Comment by yawhide** [comment]
Hey! Great suggestion, I'll take a look. I'll respond here once it is live.

**Comment by yawhide** [comment]
Also, just to note, this won't help (yet) accurately describe the fees for Newton as they have their own rules on how many sats/byte they use.

**Comment by yawhide** [comment]
live in production, thanks
